version: '3.4'

services:
  game_service:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:8080"
      - "8083:8081" 
    depends_on:
      - sqlserv_game
    networks:
      - produktnetwork
    restart: on-failure

  sqlserv_game:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
        MSSQL_SA_PASSWORD: "Pa$$word123!@#"
        ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_game:/var/opt/game_service_sqlserver
    networks:
      - produktnetwork
networks:
  produktnetwork:    

volumes:
  sqlserver_game:    